Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,14 +1,38 @@
-stages:          # List of stages for jobs, and their order of execution
+stages:
   - build
-  - test
   - deploy
 
-deploy-prod-server:
+
+build-backend:
+  stage: build
+  variables:
+    APP_NAME: pythonAI
+  before_script:
+    - export TAG="latest-${CI_COMMIT_SHORT_SHA}"
+    - echo "Logging into registry $CI_REGISTRY..."
+    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY" && echo "Docker login succeeded" || { echo "Docker login failed"; exit 1; }
+  script:
+    - echo "Building $APP_NAME image..."
+    - export IMAGE_NAME="$CI_REGISTRY_IMAGE/$APP_NAME"
+    - docker build -t $IMAGE_NAME:$TAG .
+    - echo "Pushing $IMAGE_NAME:$TAG..."
+    - docker push $IMAGE_NAME:$TAG
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "main"'
+      when: always
+  allow_failure: false
+  tags:
+    - docker:dind
+
+
+deploy-server:
   stage: deploy
-  image: alpine:latest
 
   variables:
-    DOCKER_COMPOSE_FILE: "/data/docker/$CI_PROJECT_NAME.yml"
+    DOCKER_COMPOSE_DIR: "~/docker-files"
+    DOCKER_COMPOSE_FILE: "$CI_PROJECT_NAME.yml"
+
+
 
   before_script:
     - apk add --no-cache openssh-client bash curl
@@ -17,50 +41,45 @@ deploy-prod-server:
     - mkdir -p ~/.ssh
     - chmod 700 ~/.ssh
     - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
-
+    - export DEPLOY_SERVER="$USER_SSH@$IP_SERVER"
+    - export DOCKER_COMPOSE_NAME="docker-compose.yml"
+    - export TAG="latest-${CI_COMMIT_SHORT_SHA}"
+    - export CURL_URL="https://gitlab.stemdev.uz/api/v4/projects/$CI_PROJECT_ID/repository/files/$DOCKER_COMPOSE_NAME/raw?ref=$CI_COMMIT_REF_NAME"
   script:
     - |
-      if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
-        export DOCKER_COMPOSE_NAME="docker-compose.prod.yml"
-      elif [ "$CI_COMMIT_REF_NAME" == "dev" ]; then
-        export DOCKER_COMPOSE_NAME="docker-compose.stage.yml"
-      else
-        echo "Error: Unsupported branch $CI_COMMIT_REF_NAME"
-        exit 1
-      fi
-    - export CURL_URL=""
-    - export TAG="$([ "$CI_COMMIT_REF_NAME" == "main" ] && echo "latest-${CI_COMMIT_SHORT_SHA}" || echo "stage-${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}")"
-    - |
-      ssh -T $PROD_SERVER "
+      ssh -T $DEPLOY_SERVER "
         echo '=== Prepare environment ==='
-        echo \"DOCKER_COMPOSE_FILE: $DOCKER_COMPOSE_FILE\"
+        echo \"DOCKER_COMPOSE: $DOCKER_COMPOSE_DIR/$DOCKER_COMPOSE_FILE\"
         echo \"CURL_URL: $CURL_URL\"
         echo \"TAG: $TAG\"
-        mkdir -p "$(dirname "$DOCKER_COMPOSE_FILE")"
+        mkdir -p "$(dirname "$DOCKER_COMPOSE_DIR")"
       
         echo '=== Download docker-compose file ==='
         echo "Trying to download: $CURL_URL"
-        curl --fail --location --header \"PRIVATE-TOKEN: ${GIT_ACCESS_TOKEN:-$CI_JOB_TOKEN}\" -o \"$DOCKER_COMPOSE_FILE\" \"$CURL_URL\"
+        curl --fail --location --header \"PRIVATE-TOKEN: ${GIT_ACCESS_TOKEN:-$CI_JOB_TOKEN}\" -o \"$DOCKER_COMPOSE_DIR/$DOCKER_COMPOSE_FILE\" \"$CURL_URL\"
+      
       
         echo '=== Docker login... ==='
         echo \"$CI_REGISTRY_PASSWORD\" | docker login -u \"$CI_REGISTRY_USER\" --password-stdin \"$CI_REGISTRY\" && echo 'Docker login succeeded' || { echo 'Docker login failed'; exit 1; }
       
         echo '=== Stop and remove existing containers ==='
-        docker compose -f . down || true
+        docker compose -f \"$DOCKER_COMPOSE_DIR/$DOCKER_COMPOSE_FILE\" down || true
       
         echo "=== Pull new images ==="
-        for APP_NAME in frontend backend; do
+        for APP_NAME in backend; do
           docker pull \"$CI_REGISTRY_IMAGE/\$APP_NAME:$TAG\"
         done
       
         echo "=== Start new containers ==="
-        docker compose -f . up -d
+        docker compose -f \"$DOCKER_COMPOSE_DIR/$DOCKER_COMPOSE_FILE\" up -d
       "
-  environment: production
   needs:
-    - build-frontend
     - build-backend
   rules:
-    - if: '$CI_COMMIT_REF_NAME == "main"'
+    - if: '$CI_COMMIT_BRANCH == "main"'
       when: manual
+    - when: never
   allow_failure: false
+  tags:
+    - docker:dind
+  
