Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,37 +3,69 @@ stages:          # List of stages for jobs, and their order of execution
   - test
   - deploy
 
-build-job:       # This job runs in the build stage, which runs first.
-  stage: build
-  script:
-    - echo "Compiling the code..."
-    - echo "Compile complete."
-  tags:
-    - docker:dind
+deploy-prod-server:
+  stage: deploy
+  image: alpine:latest
 
-unit-test-job:   # This job runs in the test stage.
-  stage: test    # It only starts when the job in the build stage completes successfully.
-  script:
-    - echo "Running unit tests... This will take about 60 seconds."
-    - sleep 60
-    - echo "Code coverage is 90%"
-  tags:
-    - docker:dind
+  variables:
+    DOCKER_COMPOSE_FILE: "/data/docker/$CI_PROJECT_NAME.yml"
 
-lint-test-job:   # This job also runs in the test stage.
-  stage: test    # It can run at the same time as unit-test-job (in parallel).
-  script:
-    - echo "Linting code... This will take about 10 seconds."
-    - sleep 10
-    - echo "No lint issues found."
-  tags:
-    - docker:dind
+  before_script:
+    - apk add --no-cache openssh-client bash curl
+    - eval $(ssh-agent -s)
+    - echo "$SSH_PROD_PRIVATE_KEY" | tr -d '\r' | ssh-add -
+    - mkdir -p ~/.ssh
+    - chmod 700 ~/.ssh
+    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
 
-deploy-job:      # This job runs in the deploy stage.
-  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
+  script:
+    - |
+      if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
+        export DOCKER_COMPOSE_NAME="docker-compose.prod.yml"
+      elif [ "$CI_COMMIT_REF_NAME" == "dev" ]; then
+        export DOCKER_COMPOSE_NAME="docker-compose.stage.yml"
+      else
+        echo "Error: Unsupported branch $CI_COMMIT_REF_NAME"
+        exit 1
+      fi
+    - export CURL_URL="https://gitlab.sarapuloff-team.com/api/v4/projects/$CI_PROJECT_ID/repository/files/$DOCKER_COMPOSE_NAME/raw?ref=$CI_COMMIT_REF_NAME"
+    - export TAG="$([ "$CI_COMMIT_REF_NAME" == "main" ] && echo "latest-${CI_COMMIT_SHORT_SHA}" || echo "stage-${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}")"
+    - |
+      ssh -T $PROD_SERVER "
+        echo '=== Prepare environment ==='
+        echo \"DOCKER_COMPOSE_FILE: $DOCKER_COMPOSE_FILE\"
+        echo \"CURL_URL: $CURL_URL\"
+        echo \"TAG: $TAG\"
+        mkdir -p "$(dirname "$DOCKER_COMPOSE_FILE")"
+      
+        echo '=== Download docker-compose file ==='
+        echo "Trying to download: $CURL_URL"
+        curl --fail --location --header \"PRIVATE-TOKEN: ${GIT_ACCESS_TOKEN:-$CI_JOB_TOKEN}\" -o \"$DOCKER_COMPOSE_FILE\" \"$CURL_URL\"
+      
+        echo '=== Replace image tags in compose file ==='
+        for APP_NAME in frontend backend; do
+          sed -i \"s|image: *sarapuloff-\$APP_NAME|image: $CI_REGISTRY_IMAGE/\$APP_NAME:$TAG|g\" \"$DOCKER_COMPOSE_FILE\"
+        done
+      
+        echo '=== Docker login... ==='
+        echo \"$CI_REGISTRY_PASSWORD\" | docker login -u \"$CI_REGISTRY_USER\" --password-stdin \"$CI_REGISTRY\" && echo 'Docker login succeeded' || { echo 'Docker login failed'; exit 1; }
+      
+        echo '=== Stop and remove existing containers ==='
+        docker compose -f \"$DOCKER_COMPOSE_FILE\" down || true
+      
+        echo "=== Pull new images ==="
+        for APP_NAME in frontend backend; do
+          docker pull \"$CI_REGISTRY_IMAGE/\$APP_NAME:$TAG\"
+        done
+      
+        echo "=== Start new containers ==="
+        docker compose -f \"$DOCKER_COMPOSE_FILE\" up -d
+      "
   environment: production
-  script:
-    - echo "Deploying application..."
-    - echo "Application successfully deployed."
-  tags:
-    - docker:dind
+  needs:
+    - build-frontend
+    - build-backend
+  rules:
+    - if: '$CI_COMMIT_REF_NAME == "main"'
+      when: manual
+  allow_failure: false
